import { Onest } from 'next/font/google'
import React from "react";
import "./globals.css";
import { CartProvider } from '@/contaxt/CartContext';
// import { CartProvider } from '@/contaxt/CartContext';
import Header from '@/Ui/Header';
import NavBar from '@/Ui/NavBar';
import Footer from '@/Ui/Footer';


 
const onestSuns = Onest({
  // weight: '400',
  subsets: ['latin'],
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${onestSuns.className}`}>
        <CartProvider>
          <Header/>
          <NavBar/>
        {children}
         <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
